# Generated by Django 2.2.6 on 2020-08-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('dataslug', models.TextField(null=True)),
                ('indexed', models.BooleanField(default=False)),
                ('loaded', models.BooleanField(default=False)),
                ('graph', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('indexed', models.BooleanField(default=False)),
                ('loaded', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Dataset')),
            ],
        ),
    ]
