# Generated by Django 2.2.6 on 2020-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_threadtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadtask',
            name='task',
        ),
        migrations.AddField(
            model_name='threadtask',
            name='name',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
    ]
