# Generated by Django 2.2.6 on 2020-01-17 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200117_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtask',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='threadtask',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
