# Generated by Django 2.2.6 on 2020-01-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200117_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='title',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
            ],
        ),
    ]
