# Generated by Django 2.2.6 on 2020-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200123_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtask',
            name='status_ok',
            field=models.BooleanField(default=True),
        ),
    ]
