# Generated by Django 2.2.6 on 2020-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_threadtask_status_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
