# Generated by Django 2.2.6 on 2020-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_dataset_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='graph',
            field=models.TextField(null=True),
        ),
    ]
