# Generated by Django 2.2.6 on 2020-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_dataset_dataslug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datafile',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
